### ISSUE TITLE
Unable to project on MacOS

### ISSUE THREAD

**Issue by h4rdmol** [JanSeliv/Bomber#62]
![image](https://user-images.githubusercontent.com/5227233/210271031-14751467-6826-44e4-968e-ae783ddb362f.png)

![image](https://user-images.githubusercontent.com/5227233/210278972-d97a1083-2e24-4875-9f40-0e90c5179232.png)

Logs from build: 
[Logs.txt](https://github.com/JanSeliv/Bomber/files/10333509/Logs.txt)

**Comment by JanSeliv** [comment]
I've fixed those errors and managed to cook the build for UE5.2 for MacOS. Please download native UE5.2 from Epic Games launcher to successfully build and launch the project
