### ISSUE TITLE
Source corrupted

### ISSUE THREAD

**Issue by joopss** [JanSeliv/Bomber#65]
one texture is corrupted 7zip and rar is not working to extract.

**Comment by JanSeliv** [comment]
Hey.

Which texture exactly is corrupted and which archive?

- If archive is Bomber build from release page, you can find it has 2 parts, so both of them have to be downloaded first, then extracting .zip.001 will automatically extract zip.002 as well. I just did it it and was able to run extracted build with no issues:
![image](https://github.com/JanSeliv/Bomber/assets/20540872/161a25d6-7e1e-43c0-8dea-6de3adb8ad95)

- if archive is repo downloaded from GitHub as zip, then download it from git terminal instead through SSH (read readme and [Issue](https://github.com/JanSeliv/Bomber/issues/64)).

**Comment by joopss** [comment]
![Screenshot 2023-12-29 120421](https://github.com/JanSeliv/Bomber/assets/39462860/982a4739-1c3b-43d7-9333-6b484fd08b46)
![Screenshot 2023-12-29 115353](https://github.com/JanSeliv/Bomber/assets/39462860/bdc5708d-8456-4b58-b8d8-19fe8ab0a8d9)

**Comment by JanSeliv** [comment]
I just recorded a video showing the downloading, extracting and running the game. Please see it here: [video](https://github.com/JanSeliv/Bomber/assets/20540872/7e387f78-3d36-46de-8c4b-f87a68709915)

If the issue still occurs on your side, feel free to reach out to me on Telegram ([t.me/JanSeliv](t.me/JanSeliv)), and I will give you the key on Steam from our private page.

**Comment by joopss** [comment]
i'm not downloading the client the Source code un ziping the source code (zip) second screenshot mark with red
I now the client works

**Comment by JanSeliv** [comment]
`Source code (zip)` is something that GitHub automatically adds to each Release. As developer, I don't have this archive included as well as I can't remove it from there.

I suspect, it attempts to download the whole repository but fails on limit of zip size, so you have archived corrupted.

Any Release page is designed to provide builds (clients) to other developers. While the `source` (project itself) you have to download in normal way: from git clone command as mentioned in readme
